### PR TITLE
Support the new JSX transform

### PR DESCRIPTION
**Pull request by joshwooding**
- Bump esbuild from 0.14.42 to 0.14.51
- Switch to using "jsx": "react-jsx" essentially reverting https://github.com/jpmorganchase/modular/pull/502

### CODE REVIEW

**Comment by joshwooding** [comment]
Test is failing because skypack isn't compatible with the new transform esm.sh is though. If we can be a bit less opinionated we can just rely on the jsx option in tsconfig which would fix the test but users might run into this in the future.

**Comment by joshwooding** [comment]
Swapped to using a opt-in approach via the tsConfig to prevent errors when using the esm view

**Comment by sgb-io** [comment]
Hi @joshwooding, a fixed version is open here: #1998

**Comment by sgb-io** [comment]
Superseded by #1998

**Pull request closed without merging**
