### PR TITLE
fixed typo in readme

### PR DESCRIPTION
**Pull request by telamonian**
removed some repeated text from the end

### CODE REVIEW

**Review by threepointone — APPROVED** [review]
Thanks for this! We haven't setup a CLA process yet, I'm planning on doing so early next week, so I'll hold off on merging this till then.

**Comment by threepointone** [comment]
You don't need to add a changeset for this.

**Comment by telamonian** [comment]
> We haven't setup a CLA process yet

Since this is a non-critical fix, I'd recommend that you close this PR for the time being and instead take a moment to consider whether you really need a CLA. In general, they offer no benefits while also creating a hostile environment for contributors. CLAs are:

- of limited legal relevance; no CLA has ever been tested in a court of law
- broadly considered to be [bad for open source](https://www.linuxjournal.com/content/contributor-agreements-considered-harmful) in general
- unwelcoming to both new and experienced contributors

As a rule, I never sign any CLA, as they have been used in the past to justify [actions carried out in bad faith](https://drewdevault.com/2021/01/19/Elasticsearch-does-not-belong-to-Elastic.html)

**Comment by LukeSheard** [comment]
I've fixed this directly so I'm closing this PR now.

**Pull request closed without merging**
